/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectosalud.gui;

import java.time.LocalDate;

import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.TextStyle;
import java.util.Locale;

/**
 *
 * @author mac
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
 
    public Dashboard() {

        initComponents();
        initStyles();
        fechamodificada();
    
        // pasar referencia de este dashboard a vista login  enla variable vs

    }

    public void fechamodificada() {
        LocalDate fechaActual = LocalDate.now();
        int dia = fechaActual.getDayOfMonth();
        Month mes = fechaActual.getMonth();
        int año = fechaActual.getYear();
        String nombreMes = mes.getDisplayName(TextStyle.FULL, new Locale("es", "ES"));
        String nombreMesMayus = nombreMes.toUpperCase();

        String fecha01 = "HOY ES " + dia + " DE " + nombreMesMayus + " DEL " + año;
        fecha.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        fecha.setText(fecha01);
    }

    public void initStyles() {
        mensaje.putClientProperty("FlatLaf.style", "font: 14 $light.font");
        mensaje.setForeground(Color.BLACK);
        administracion.putClientProperty("FlatLaf.style", "font: bold $h3.font");
        administracion.setForeground(Color.BLACK);
        fecha.putClientProperty("FlatLaf.style", "font: $h0.font ");
        fecha.setForeground(Color.white);
        textopanel.putClientProperty("FlatLaf.style", "font: bold $h1.font");
        textopanel.setForeground(Color.white);
        botonsalir.putClientProperty("FlatLaf.style", "font: bold $large.font");

        bienvenida.putClientProperty("FlatLaf.style", "font: bold $h3.font");
        jLabel3.putClientProperty("FlatLaf.style", "font: semibold $large.font");
        jLabel4.putClientProperty("FlatLaf.style", "font: semibold $large.font");
        jLabel5.putClientProperty("FlatLaf.style", "font: semibold $large.font");
        jLabel6.putClientProperty("FlatLaf.style", "font: semibold $large.font");
        jLabel7.putClientProperty("FlatLaf.style", "font: semibold $large.font");
        jLabel8.putClientProperty("FlatLaf.style", "font: semibold $large.font");
        jLabel9.putClientProperty("FlatLaf.style", "font: semibold $large.font");
                jLabel10.putClientProperty("FlatLaf.style", "font: semibold $large.font");
                        jLabel11.putClientProperty("FlatLaf.style", "font: semibold $large.font");
        jLabel12.putClientProperty("FlatLaf.style", "font: semibold $large.font");



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        imagenprincipal = new javax.swing.JLabel();
        bienvenida = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelbotones = new javax.swing.JPanel();
        textopanel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonagendar = new javax.swing.JButton();
        botonmodificar = new javax.swing.JButton();
        botonconsultar = new javax.swing.JButton();
        botonhistoriaclinica = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        administracion = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1249, 706));
        setName("framedashboard"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMinimumSize(new java.awt.Dimension(650, 382));
        content.setPreferredSize(new java.awt.Dimension(650, 382));

        imagenprincipal.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/Programacion/ProyectoSalud/src/main/Recursos/portadasalud.jpg")); // NOI18N
        imagenprincipal.setText("jLabel2");

        bienvenida.setText("Cordial Saludo!!!");

        jLabel3.setText("Bienvenido a nuestra innovadora plataforma de gestión de citas medicas. ");

        jLabel4.setText("con esta plataforma simplificamos el proceso de asginacion de citas, y mejoramos la ");

        jLabel6.setText("experiencia tanto para pacientes como para los Profesionales de la salud. Aqui te ");

        jLabel8.setText("ofrecemos un vistazo de lo que nuestra aplicacion puede hacer ti.");

        jLabel10.setText("• Ofrece flexibilidad al permitirte programar citas según tu disponibilidad ");

        jLabel11.setText("• Visualiza información detallada sobre los médicos disponibles");

        jLabel12.setText("•Experimenta una experiencia fluida y sin complicaciones en la gestión de tus citas ");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(355, 355, 355))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(390, 390, 390))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(bienvenida)
                .addGap(83, 83, 83)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(149, 149, 149))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagenprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        panelbotones.setBackground(new java.awt.Color(13, 71, 161));

        textopanel.setFont(new java.awt.Font("AppleMyungjo", 1, 20)); // NOI18N
        textopanel.setForeground(new java.awt.Color(255, 255, 255));
        textopanel.setText("Panel De Control");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        botonagendar.setBackground(new java.awt.Color(21, 101, 192));
        botonagendar.setFont(new java.awt.Font("AppleMyungjo", 0, 18)); // NOI18N
        botonagendar.setForeground(new java.awt.Color(255, 255, 255));
        botonagendar.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/Programacion/ProyectoSalud/src/main/Recursos/lapiz.png")); // NOI18N
        botonagendar.setText("Agendar Cita Medica");
        botonagendar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonagendar.setBorderPainted(false);
        botonagendar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonagendar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonagendar.setIconTextGap(10);
        botonagendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonagendarMousePressed(evt);
            }
        });
        botonagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonagendarActionPerformed(evt);
            }
        });

        botonmodificar.setBackground(new java.awt.Color(21, 101, 192));
        botonmodificar.setFont(new java.awt.Font("AppleMyungjo", 0, 18)); // NOI18N
        botonmodificar.setForeground(new java.awt.Color(255, 255, 255));
        botonmodificar.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/Programacion/ProyectoSalud/src/main/Recursos/calendario.png")); // NOI18N
        botonmodificar.setText("Modificar Cita Medica");
        botonmodificar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonmodificar.setBorderPainted(false);
        botonmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonmodificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonmodificar.setIconTextGap(10);
        botonmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonmodificarMousePressed(evt);
            }
        });

        botonconsultar.setBackground(new java.awt.Color(21, 101, 192));
        botonconsultar.setFont(new java.awt.Font("AppleMyungjo", 0, 18)); // NOI18N
        botonconsultar.setForeground(new java.awt.Color(255, 255, 255));
        botonconsultar.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/Programacion/ProyectoSalud/src/main/Recursos/buscar-alt.png")); // NOI18N
        botonconsultar.setText("Consultar Cita Medica");
        botonconsultar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonconsultar.setBorderPainted(false);
        botonconsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonconsultar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonconsultar.setIconTextGap(10);
        botonconsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonconsultarMousePressed(evt);
            }
        });
        botonconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonconsultarActionPerformed(evt);
            }
        });

        botonhistoriaclinica.setBackground(new java.awt.Color(21, 101, 192));
        botonhistoriaclinica.setFont(new java.awt.Font("AppleMyungjo", 0, 18)); // NOI18N
        botonhistoriaclinica.setForeground(new java.awt.Color(255, 255, 255));
        botonhistoriaclinica.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/Programacion/ProyectoSalud/src/main/Recursos/documento-firmado.png")); // NOI18N
        botonhistoriaclinica.setText("Historia Clinica");
        botonhistoriaclinica.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        botonhistoriaclinica.setBorderPainted(false);
        botonhistoriaclinica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonhistoriaclinica.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonhistoriaclinica.setIconTextGap(10);
        botonhistoriaclinica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonhistoriaclinicaMousePressed(evt);
            }
        });
        botonhistoriaclinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonhistoriaclinicaActionPerformed(evt);
            }
        });

        botonsalir.setText("SALIR");
        botonsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonsalirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelbotonesLayout = new javax.swing.GroupLayout(panelbotones);
        panelbotones.setLayout(panelbotonesLayout);
        panelbotonesLayout.setHorizontalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonagendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonconsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonhistoriaclinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbotonesLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelbotonesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(textopanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)))
                .addGap(49, 49, 49))
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelbotonesLayout.setVerticalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(textopanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(botonagendar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonhistoriaclinica, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(botonsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));

        administracion.setText("Administracion/Control/CitasMedicas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(administracion, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(administracion)
                .addGap(18, 18, 18)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mensaje.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/Programacion/ProyectoSalud/src/main/Recursos/ajustes.png")); // NOI18N
        mensaje.setText("SubGurupo 14, GPI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(panelbotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelbotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );

        content.getAccessibleContext().setAccessibleName("");
        content.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonhistoriaclinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonhistoriaclinicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonhistoriaclinicaActionPerformed

    private void botonhistoriaclinicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonhistoriaclinicaMousePressed
        // TODO add your handling code here:

        initBotonDescargarHistoriaClinica();

    }//GEN-LAST:event_botonhistoriaclinicaMousePressed

    private void botonconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonconsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonconsultarActionPerformed

    private void botonconsultarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonconsultarMousePressed
        // TODO add your handling code here:
        initPanelConsultar();


    }//GEN-LAST:event_botonconsultarMousePressed


    private void botonmodificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonmodificarMousePressed

        try {
            initPanelModCita();
            
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_botonmodificarMousePressed

    private void botonsalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonsalirMousePressed

        // TODO add your handling code here:
        dispose();


    }//GEN-LAST:event_botonsalirMousePressed

    private void botonagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonagendarActionPerformed
        try {
            // TODO add your handling code here:

            initAgendarCita();
           
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_botonagendarActionPerformed

    public void botonesDesactivados() {
        botonmodificar.setVisible(false);
        botonagendar.setVisible(false);
        botonconsultar.setVisible(false);
        botonhistoriaclinica.setVisible(false);

    }

    public void botonesActivados() {
        botonmodificar.setVisible(true);
        botonagendar.setVisible(true);
        botonconsultar.setVisible(true);
        botonhistoriaclinica.setVisible(true);
    }

    private void botonagendarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonagendarMousePressed


    }//GEN-LAST:event_botonagendarMousePressed

    public void initPanelModCita() throws SQLException, ClassNotFoundException {

        VistaModificar md = new VistaModificar();
        md.setSize(900,900);
        md.setLocation(0, 0);
        md.revalidate();
        md.repaint();
        content.removeAll();
        content.add(md,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }

    public void initPanelConsultar() {

        // Crear una instancia del JPanel VistaConsultar
        VistaConsultar vistaConsultar = new VistaConsultar();

        // Configurar el tamaño y la ubicación del JPanel VistaConsultar
        vistaConsultar.setSize(900,900);
        vistaConsultar.setLocation(0, 0);

        // Agregar el JPanel VistaConsultar al JPanel content
        content.removeAll();
        content.add(vistaConsultar, BorderLayout.CENTER);

        // Actualizar la interfaz de usuario del JPanel content
        content.revalidate();
        content.repaint();
    }

    public void initBotonDescargarHistoriaClinica() {

        VistaDescargaHistoriaClinica vs = new VistaDescargaHistoriaClinica();

        vs.setSize(900,900);
        vs.setLocation(0, 0);
        content.removeAll();

        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }

    public void initAgendarCita() throws SQLException, ClassNotFoundException {
        VistaAgendar vs = new VistaAgendar();
        vs.setSize(900, 900);
        vs.setLocation(0, 0);
        vs.revalidate();
        vs.repaint();
        content.removeAll();
        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
         */

 /*     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         */

FlatMaterialLighterIJTheme.setup();
        UIManager.put("Button.arc", 999);
        UIManager.put( "Component.arc", 999 );
        UIManager.put( "Component.arrowType", "triangle" );
        UIManager.put( "TextComponent.arc", 999 );
        System.setProperty( "apple.awt.application.name", "GESTOR CITAS MEDICAS" );
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new Dashboard().setVisible(true);
                //      VistaLogin vistaLogin = new VistaLogin(dashboard);
                //     vistaLogin.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administracion;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton botonagendar;
    private javax.swing.JButton botonconsultar;
    private javax.swing.JButton botonhistoriaclinica;
    private javax.swing.JButton botonmodificar;
    private javax.swing.JButton botonsalir;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel imagenprincipal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel panelbotones;
    private javax.swing.JLabel textopanel;
    // End of variables declaration//GEN-END:variables
}
