/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectosalud.gui;
import PDFhistoriasclinicas.Imagenes;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author mac
 */
public class InsertarHistoriaClinica extends javax.swing.JPanel {

    /**
     * Creates new form VistaDescargaHistoriaClinica
     */
 
    
    public InsertarHistoriaClinica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelprincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombrefield = new javax.swing.JTextField();
        cedulafield = new javax.swing.JTextField();
        botoninsertarhistoria = new javax.swing.JButton();
        botonatras = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("INGRESE NOMBRE");

        jLabel2.setText("INGRESE CEDULA");

        nombrefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrefieldActionPerformed(evt);
            }
        });

        botoninsertarhistoria.setText("INSERTAR");
        botoninsertarhistoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botoninsertarhistoriaMousePressed(evt);
            }
        });

        botonatras.setText("ATRAS");
        botonatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonatrasMousePressed(evt);
            }
        });
        botonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelprincipalLayout = new javax.swing.GroupLayout(panelprincipal);
        panelprincipal.setLayout(panelprincipalLayout);
        panelprincipalLayout.setHorizontalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addComponent(botoninsertarhistoria)
                        .addGap(82, 82, 82)
                        .addComponent(botonatras))
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(120, 120, 120)
                        .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cedulafield, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(nombrefield))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelprincipalLayout.setVerticalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombrefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cedulafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoninsertarhistoria)
                    .addComponent(botonatras))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initBotonAtras() {
   //      JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(panelprincipal);

        Dashboard ds = new Dashboard();
        ds.setVisible(true);
        ds.revalidate();
        ds.repaint();
    }
    private void botoninsertarhistoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoninsertarhistoriaMousePressed
        // TODO add your handling code here:

        String nombre = nombrefield.getText();
        String cedula = cedulafield.getText();
        File archivoPDF = new File("/Users/mac/NetBeansProjects/Programacion/ProyectoSalud/src/main/java/PDFhistoriasclinicas/MODELO-DE-HC.pdf");
        try {
            AccesoDatos ac = new AccesoDatos();
            ac.agregarHistoriaClinicaPDF(nombre, cedula, archivoPDF);

            //  ac.descargarHistoriaClinicaPDF(nombre, cedula);
        } catch (SQLException ex) {
            Logger.getLogger(InsertarHistoriaClinica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InsertarHistoriaClinica.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botoninsertarhistoriaMousePressed

    private void botonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonatrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonatrasActionPerformed

    private void botonatrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonatrasMousePressed
        // TODO add your handling code here:
        initBotonAtras();

    }//GEN-LAST:event_botonatrasMousePressed

    private void nombrefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrefieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonatras;
    private javax.swing.JButton botoninsertarhistoria;
    private javax.swing.JTextField cedulafield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrefield;
    private javax.swing.JPanel panelprincipal;
    // End of variables declaration//GEN-END:variables
}
