/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectosalud.gui;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Time;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author mac
 */
public class VistaAgendar extends javax.swing.JPanel {



    /**
     * Creates new form VistaAgendar
     */
    public VistaAgendar() throws SQLException, ClassNotFoundException {
        initComponents();
        initStyles();
        llenarEspecialistasComboBox();
        llenarHoraComboBox();
    }

    public void initStyles() {

        inicio.putClientProperty("FlatLaf.style", "font: bold $h1.font");
        inicio.setForeground(Color.BLACK);
        nombrefield.putClientProperty("FlatLaf.style", "font: $medium.font");
        nombrefield.setForeground(Color.GRAY);
        cedulafield1.putClientProperty("FlatLaf.style", "font: $medium.font");
        cedulafield1.setForeground(Color.GRAY);
        motivofield1.putClientProperty("FlatLaf.style", "font: $medium.font");
        motivofield1.setForeground(Color.GRAY);
            botonagendar.putClientProperty("FlatLaf.style", "font: bold $h3.font");
            botonagendar.setForeground(Color.BLACK);
            botonatras.putClientProperty("FlatLaf.style", "font: bold $h3.font");
             botonatras.setForeground(Color.BLACK);
        panelprincipal.revalidate();
        panelprincipal.repaint();
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombrefield = new javax.swing.JTextField();
        cedulafield1 = new javax.swing.JTextField();
        motivofield1 = new javax.swing.JTextField();
        especialistacombobox = new javax.swing.JComboBox<>();
        horacombobox = new javax.swing.JComboBox<>();
        botonagendar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        datefield = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        inicio = new javax.swing.JLabel();
        botonatras = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(650, 382));

        panelprincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelprincipal.setPreferredSize(new java.awt.Dimension(650, 382));

        jLabel1.setText("Nombre De Usuario");

        jLabel2.setText("Cedula");

        jLabel4.setText("Especialistas Disponibles");

        jLabel5.setText("Hora Disponible");

        jLabel6.setText("Motivo De Consulta");

        nombrefield.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        nombrefield.setText("Ingrese nombre de usuario");
        nombrefield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombrefield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombrefieldMousePressed(evt);
            }
        });
        nombrefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrefieldActionPerformed(evt);
            }
        });

        cedulafield1.setText("Ingrese numero de documento");
        cedulafield1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cedulafield1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cedulafield1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cedulafield1MouseReleased(evt);
            }
        });
        cedulafield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulafield1ActionPerformed(evt);
            }
        });

        motivofield1.setText("Ingrese motivo de la consulta");
        motivofield1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                motivofield1MousePressed(evt);
            }
        });
        motivofield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motivofield1ActionPerformed(evt);
            }
        });

        especialistacombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        especialistacombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialistacomboboxActionPerformed(evt);
            }
        });

        horacombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        horacombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horacomboboxActionPerformed(evt);
            }
        });

        botonagendar.setBackground(new java.awt.Color(204, 204, 204));
        botonagendar.setFont(new java.awt.Font("AppleMyungjo", 0, 18)); // NOI18N
        botonagendar.setText("Agendar Cita Medica");
        botonagendar.setAutoscrolls(true);
        botonagendar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonagendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonagendarMousePressed(evt);
            }
        });
        botonagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonagendarActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha");

        inicio.setBackground(new java.awt.Color(153, 153, 153));
        inicio.setFont(new java.awt.Font("AppleMyungjo", 0, 18)); // NOI18N
        inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio.setText("Agendamiento Cita Medica");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        botonatras.setBackground(new java.awt.Color(204, 204, 204));
        botonatras.setFont(new java.awt.Font("AppleMyungjo", 0, 18)); // NOI18N
        botonatras.setText("Atras");
        botonatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonatrasMousePressed(evt);
            }
        });
        botonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelprincipalLayout = new javax.swing.GroupLayout(panelprincipal);
        panelprincipal.setLayout(panelprincipalLayout);
        panelprincipalLayout.setHorizontalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelprincipalLayout.createSequentialGroup()
                                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombrefield)
                                    .addComponent(cedulafield1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)))
                            .addGroup(panelprincipalLayout.createSequentialGroup()
                                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelprincipalLayout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addComponent(botonagendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(86, 86, 86)
                                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(horacombobox, 0, 370, Short.MAX_VALUE)
                                    .addComponent(especialistacombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(motivofield1)
                                    .addComponent(botonatras, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 74, Short.MAX_VALUE))))
        );
        panelprincipalLayout.setVerticalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addComponent(nombrefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cedulafield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especialistacombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(horacombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motivofield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonatras, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonagendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
  private void llenarHoraComboBox() {
// borrar items predeterminados
      horacombobox.removeAllItems();

        // Llenar el ComboBox con horas disponibles, por ejemplo, de 8:00 AM a 5:00 PM
        for (int hour = 8; hour <= 17; hour++) {
            for (int minute = 0; minute <= 45; minute += 15) {
                LocalTime time = LocalTime.of(hour, minute);

                horacombobox.addItem(time.toString());
            }
        }
    }

    public void llenarEspecialistasComboBox() throws SQLException, ClassNotFoundException {
        AccesoDatos accesoDatos = new AccesoDatos();
        ArrayList<String> nombresEspecialistas = accesoDatos.obtenerNombresEspecialistas();

        String[] nombresArray = nombresEspecialistas.toArray(new String[0]);

        especialistacombobox.setModel(new DefaultComboBoxModel<>(nombresArray));
    }
    private void nombrefieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrefieldMousePressed
        // TODO add your handling code here:

        nombrefield.setText("");


    }//GEN-LAST:event_nombrefieldMousePressed

    private void nombrefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrefieldActionPerformed

    }//GEN-LAST:event_nombrefieldActionPerformed

    private void cedulafield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulafield1ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_cedulafield1ActionPerformed

    private void horacomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horacomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horacomboboxActionPerformed

    private void botonagendarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonagendarMousePressed

        try {
            ConexionBD cn = new ConexionBD();
            Connection conexion = cn.conexion();
            AccesoDatos ac = new AccesoDatos();

            String nombresql = nombrefield.getText();
            String cedulasql = cedulafield1.getText();
            String especialistasql = (String) especialistacombobox.getSelectedItem();
            java.util.Date fechaUtil = datefield.getDate();
            java.sql.Date fechasql = new java.sql.Date(fechaUtil.getTime());

            String horaStr = (String) horacombobox.getSelectedItem();
            LocalTime localtime = LocalTime.parse(horaStr);
            Time horasql = Time.valueOf(localtime);

            String motivosql = motivofield1.getText();

            if (ac.validarCitaMedico(conexion, fechasql, horasql, especialistasql)) {
                 ac.guardarCitas(conexion, fechasql, horasql, motivosql, nombresql, cedulasql, especialistasql);
            JOptionPane.showMessageDialog(this, " Cita agendada para " + nombresql + " con el especialista: " + especialistasql + " El dia :" + fechasql + " Hora programada: " + horasql);
            conexion.close();
            }else{
            JOptionPane.showMessageDialog(null, "Fecha y Hora no disponible, intentelo de nuevo");}
           
        } catch (SQLException ex) {
            Logger.getLogger(VistaAgendar.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al guardar la cita: " + ex.getMessage());

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaAgendar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonagendarMousePressed

    private void botonagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonagendarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_botonagendarActionPerformed
    public void initBotonAtras() {

        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(panelprincipal);
        frame.dispose();

        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);

        dashboard.revalidate();
        dashboard.repaint();

    }
    private void botonatrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonatrasMousePressed

        initBotonAtras();

    }//GEN-LAST:event_botonatrasMousePressed

    private void botonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonatrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonatrasActionPerformed

    private void especialistacomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialistacomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialistacomboboxActionPerformed

    private void cedulafield1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedulafield1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulafield1MouseReleased

    private void cedulafield1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedulafield1MousePressed
        // TODO add your handling code here:
           cedulafield1.setText("");
    }//GEN-LAST:event_cedulafield1MousePressed

    private void motivofield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motivofield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motivofield1ActionPerformed

    private void motivofield1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motivofield1MousePressed
        // TODO add your handling code here:
        motivofield1.setText("");
    }//GEN-LAST:event_motivofield1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonagendar;
    private javax.swing.JButton botonatras;
    private javax.swing.JTextField cedulafield1;
    private com.toedter.calendar.JDateChooser datefield;
    private javax.swing.JComboBox<String> especialistacombobox;
    private javax.swing.JComboBox<String> horacombobox;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField motivofield1;
    private javax.swing.JTextField nombrefield;
    private javax.swing.JPanel panelprincipal;
    // End of variables declaration//GEN-END:variables
}
