/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectosalud.gui;
import PDFhistoriasclinicas.Imagenes;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author mac
 */
public class VistaDescargaHistoriaClinica extends javax.swing.JPanel {

    /**
     * Creates new form VistaDescargaHistoriaClinica
     */
 
    
    public VistaDescargaHistoriaClinica() {
        initComponents();
        initStyles();
    }
    public void initStyles(){
       titulo.putClientProperty("FlatLaf.style", "font: bold $h1.font");
        titulo.setForeground(Color.BLACK);
       botondescargar.putClientProperty("FlatLaf.style", "font: semibold $h3.font");
        botondescargar.setForeground(Color.BLACK);
         botonatras.putClientProperty("FlatLaf.style", "font: semibold $h3.font");
        botonatras.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelprincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombrefield = new javax.swing.JTextField();
        cedulafield = new javax.swing.JTextField();
        botonatras = new javax.swing.JButton();
        botondescargar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        botoninsertarhistoria = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("INGRESE NOMBRE");

        jLabel2.setText("INGRESE NUMERO DE CEDULA");

        nombrefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrefieldActionPerformed(evt);
            }
        });

        botonatras.setText("ATRAS");
        botonatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonatrasMousePressed(evt);
            }
        });
        botonatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonatrasActionPerformed(evt);
            }
        });

        botondescargar.setText("DESCARGAR");
        botondescargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botondescargarMousePressed(evt);
            }
        });
        botondescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondescargarActionPerformed(evt);
            }
        });

        titulo.setBackground(new java.awt.Color(153, 153, 153));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titulo.setText("Descargar Historia Clinica");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelprincipalLayout = new javax.swing.GroupLayout(panelprincipal);
        panelprincipal.setLayout(panelprincipalLayout);
        panelprincipalLayout.setHorizontalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(botondescargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonatras)
                .addGap(66, 66, 66))
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombrefield, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(cedulafield))
                .addContainerGap())
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelprincipalLayout.setVerticalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrefield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cedulafield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botondescargar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                        .addComponent(botonatras)
                        .addContainerGap())))
        );

        botoninsertarhistoria.setText("INSERTAR");
        botoninsertarhistoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botoninsertarhistoriaMousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/mac/NetBeansProjects/Programacion/ProyectoSalud/src/main/Recursos/imagedescargarhistoria.jpg")); // NOI18N
        jLabel4.setText("IMAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(botoninsertarhistoria)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botoninsertarhistoria)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initBotonAtras() {
         JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(panelprincipal);
         frame.dispose();

        Dashboard ds = new Dashboard();
        ds.setVisible(true);
        ds.revalidate();
        ds.repaint();
    }
    private void botoninsertarhistoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoninsertarhistoriaMousePressed
        // TODO add your handling code here:

        String nombre = nombrefield.getText();
        String cedula = cedulafield.getText();
        File archivoPDF = new File("/Users/mac/NetBeansProjects/Programacion/ProyectoSalud/src/main/java/PDFhistoriasclinicas/MODELO-DE-HC.pdf");
        try {
            AccesoDatos ac = new AccesoDatos();
            ac.agregarHistoriaClinicaPDF(nombre, cedula, archivoPDF);

            //  ac.descargarHistoriaClinicaPDF(nombre, cedula);
        } catch (SQLException ex) {
            Logger.getLogger(VistaDescargaHistoriaClinica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaDescargaHistoriaClinica.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botoninsertarhistoriaMousePressed

    private void botondescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondescargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botondescargarActionPerformed

    private void botondescargarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botondescargarMousePressed
        // TODO add your handling code here:
       // Desktop desktop =  Desktop.getDesktop();
       // String rutaImagen = Imagenes.rutaImagen;
          ConexionBD con;
        
        String nombre = nombrefield.getText();
        String cedula = cedulafield.getText();
         try {
            con = new ConexionBD();
        
            Connection conexion = con.conexion();
       
            AccesoDatos ac = new AccesoDatos();
          
            
       //      if (ac.validacionSql(nombre, cedula)) {
                if ( ac.descargarHistoriaClinicaPDF(conexion,nombre, cedula)) {
                 ac.mostrarHistoriaClinica(conexion);
             }
           //    
           //      System.out.println("imagen descargada");
         //    }
         //    else{
          //       JOptionPane.showMessageDialog(null, "Nombre y cedula incorrectos");
           //  }
         
         //   File file = new File(rutaImagen);
            
         //   desktop.open(file);
            
           
         } catch (SQLException ex) {
            Logger.getLogger(VistaDescargaHistoriaClinica.class.getName()).log(Level.SEVERE, null, ex);
         }   catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaDescargaHistoriaClinica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VistaDescargaHistoriaClinica.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botondescargarMousePressed

    private void botonatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonatrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonatrasActionPerformed

    private void botonatrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonatrasMousePressed
        // TODO add your handling code here:
        initBotonAtras();

    }//GEN-LAST:event_botonatrasMousePressed

    private void nombrefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrefieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonatras;
    private javax.swing.JButton botondescargar;
    private javax.swing.JButton botoninsertarhistoria;
    private javax.swing.JTextField cedulafield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombrefield;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
